### ISSUE TITLE
Please add LICENSE file.

### ISSUE THREAD

**Issue by NON906** [Budtom/MLAPI-Dissonance#1]
I want to use there codes in my project, but they are not include license file.
I don't tell if I can use it freely, because no license file in this project.
So, please add something license file.

**Comment by Budtom** [comment]
Added an MIT license, good luck with your project and I'd love a follow on twitter if you have chance :) https://twitter.com/Escape_Electric

**Comment by NON906** [comment]
Thank you for your support.
