### ISSUE TITLE
Cannot use PooledBitStream

### ISSUE THREAD

**Issue by BruceKristelijn** [Budtom/MLAPI-Dissonance#2]
Hi, I tried to use the repo with my project but PooledBitStream does no longer seem to exist. What version of MLAPI is this based on if I may ask?

**Comment by BruceKristelijn** [comment]
Ofcourse when I ask I find the way to resolve. Noticed they changed the names of classes in newer versions:
![image](https://user-images.githubusercontent.com/32113184/127163086-7009575a-887d-435e-854f-38316b13015e.png)

**Comment by Budtom** [comment]
Glad you found a fix 👍
